In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time

In [2]:

# File to Load (Remember to change these)
nfldata_csv = "C:/Users/admin/Documents/SMU/NFL-QB-Analytics/Assets/Data_Files/Cleaned_QB_data.csv"

# Read the City and Ride Data
nfldata = pd.read_csv(nfldata_csv)
nfldata.head()

   Year             Name          Season  TD Passes  Passing Yards  Wins
0  1970  Arrington, Rick  Regular Season          1            328     3
1  1970   Beathard, Pete  Regular Season          2            114     8
2  1970      Belden, Bob  Regular Season          0              0     2
3  1970  Cappleman, Bill  Regular Season          0             49     2
4  1970   Carter, Virgil      Postseason          0             64     0

In [3]:
nfldata_dt = nfldata.groupby(["Year", "Name"])["Wins"].sum().reset_index().sort_values(by = "Wins",ascending = False)

nfldata_dt

      Year                 Name  Wins
2605  2015          Newton, Cam    21
2446  2013      Wilson, Russell    21
2545  2015      Anderson, Derek    20
2663  2016     Garoppolo, Jimmy    20
2634  2015            Webb, Joe    20
1864  2007         Cassel, Matt    20
1859  2007           Brady, Tom    20
2389  2013    Jackson, Tarvaris    20
2023  2009          Brees, Drew    19
1559  2002          King, Shaun    18
1555  2002        Johnson, Brad    18
2243  2011       Rodgers, Aaron    18
608   1984      Cavanaugh, Matt    18
693   1985        Tomczak, Mike    18
2003  2008  Roethlisberger, Ben    18
2197  2011          Flynn, Matt    18
2620  2015      Siemian, Trevor    18
1557  2002         Johnson, Rob    18
2591  2015      Manning, Peyton    18
2405  2013      Manning, Peyton    18
2451  2014           Brady, Tom    18
2607  2015      Osweiler, Brock    18
1654  2004           Brady, Tom    17
2176  2011           Brady, Tom    17
2417  2013      Osweiler, Brock    17
2409  2013          McCoy, Colt    17
2208  2011         Hoyer, Brian    17
1832  2006          Orton, Kyle    17
1820  2006      Manning, Peyton    17
2219  2011        Mallett, Ryan    17
...    ...                  ...   ...
1823  2006      Matthews, Shane     0
1812  2006         Jacobs, Omar     0
1221  1996         George, Jeff     0
771   1987          Kelly, Paul     0
1765  2005        Palmer, Jesse     0
2192  2011       Edwards, Trent     0
2464  2014          Devlin, Pat     0
2463  2014     Davis, Dominique     0
2666  2016     Grayson, Garrett     0
2680  2016          Lewis, Thad     0
1932  2007           Vick, Mike     0
2440  2013    Vandenberg, James     0
777   1987       Lindley, David     0
1927  2007        Terrell, Jeff     0
2444  2013          Weber, Adam     0
2355  2012         Young, Vince     0
832   1988       Gelbaugh, Stan     0
1349  1998        Philcox, Todd     0
739   1987          Adams, Tony     0
2189  2011          Davis, Nate     0
1322  1998        Dittoe, Chris     0
481   1981          Dils, Steve     0
1310  1998          Baker, Jeff     0
1304  1997        Weldon, Casey     0
1293  1997        Philcox, Todd     0
2318  2012      Nesbitt, Joshua     0
1708  2004        Rivers, David     0
806   1987       Tinsley, Scott     0
1893  2007        Korrodi, Toby     0
1382  1999            Fox, Jeff     0

[2732 rows x 3 columns]

In [4]:
nfldata_dt = nfldata.groupby(["Year", "Name"])["Passing Yards"].sum().reset_index().sort_values(by = "Passing Yards",ascending = False)

nfldata_dt

      Year                     Name  Passing Yards
2177  2011              Brees, Drew           6854
2405  2013          Manning, Peyton           6797
2176  2011               Brady, Tom           6492
2220  2011             Manning, Eli           6466
636   1984              Marino, Dan           6224
2359  2013              Brees, Drew           6173
2708  2016               Ryan, Matt           6165
2336  2012               Ryan, Matt           5914
2495  2014             Luck, Andrew           5892
1859  2007               Brady, Tom           5889
2013  2008             Warner, Kurt           5880
1820  2006          Manning, Peyton           5853
1543  2002             Gannon, Rich           5822
2248  2011        Stafford, Matthew           5813
2057  2009          Manning, Peyton           5752
1522  2001             Warner, Kurt           5686
2269  2012              Brees, Drew           5665
2268  2012               Brady, Tom           5648
2523  2014      Roethlisberger, Ben           5617
1949  2008              Brees, Drew           5597
1414  1999             Warner, Kurt           5539
1625  2003          Manning, Peyton           5527
2608  2015           Palmer, Carson           5523
2079  2009           Rodgers, Aaron           5519
2705  2016           Rodgers, Aaron           5492
2548  2015               Brady, Tom           5489
2158  2010           Rodgers, Aaron           5486
2023  2009              Brees, Drew           5474
2243  2011           Rodgers, Aaron           5443
1789  2006              Brees, Drew           5432
...    ...                      ...            ...
1758  2005             McCown, Luke              0
1755  2005          Matthews, Shane              0
595   1983            Ransom, Brian              0
1316  1998             Cherry, Mike              0
1333  1998           Gonzalez, Pete              0
2318  2012          Nesbitt, Joshua              0
2319  2012  Newhall-Caballero, Kyle              0
593   1983           Pastorini, Dan              0
2321  2012         O'Connell, Kevin              0
1343  1998          Matthews, Shane              0
623   1984           Inverso, Glenn              0
628   1984              Kiel, Blair              0
1324  1998          Erickson, Craig              0
1322  1998            Dittoe, Chris              0
663   1985              Dils, Steve              0
659   1985        Christensen, Jeff              0
1318  1998           Delhomme, Jake              0
649   1984           Schroeder, Jay              0
646   1984               Reed, Mark              0
645   1984            Ransom, Brian              0
1768  2005             Ragone, Dave              0
643   1984           Pelluer, Steve              0
2283  2012          Enderle, Nathan              0
639   1984            Nugent, Terry              0
1765  2005            Palmer, Jesse              0
637   1984          Mathison, Bruce              0
2289  2012           Garrard, David              0
633   1984             Mackey, Kyle              0
2731  2016              Yates, T.J.              0
1463  2000              Rattay, Tim             -4

[2732 rows x 3 columns]

In [7]:
nfldata_df = pd.DataFrame(nfldata_dt)
nfldata_df

      Year                     Name  Passing Yards
2177  2011              Brees, Drew           6854
2405  2013          Manning, Peyton           6797
2176  2011               Brady, Tom           6492
2220  2011             Manning, Eli           6466
636   1984              Marino, Dan           6224
2359  2013              Brees, Drew           6173
2708  2016               Ryan, Matt           6165
2336  2012               Ryan, Matt           5914
2495  2014             Luck, Andrew           5892
1859  2007               Brady, Tom           5889
2013  2008             Warner, Kurt           5880
1820  2006          Manning, Peyton           5853
1543  2002             Gannon, Rich           5822
2248  2011        Stafford, Matthew           5813
2057  2009          Manning, Peyton           5752
1522  2001             Warner, Kurt           5686
2269  2012              Brees, Drew           5665
2268  2012               Brady, Tom           5648
2523  2014      Roethlisberger, Ben           5617
1949  2008              Brees, Drew           5597
1414  1999             Warner, Kurt           5539
1625  2003          Manning, Peyton           5527
2608  2015           Palmer, Carson           5523
2079  2009           Rodgers, Aaron           5519
2705  2016           Rodgers, Aaron           5492
2548  2015               Brady, Tom           5489
2158  2010           Rodgers, Aaron           5486
2023  2009              Brees, Drew           5474
2243  2011           Rodgers, Aaron           5443
1789  2006              Brees, Drew           5432
...    ...                      ...            ...
1758  2005             McCown, Luke              0
1755  2005          Matthews, Shane              0
595   1983            Ransom, Brian              0
1316  1998             Cherry, Mike              0
1333  1998           Gonzalez, Pete              0
2318  2012          Nesbitt, Joshua              0
2319  2012  Newhall-Caballero, Kyle              0
593   1983           Pastorini, Dan              0
2321  2012         O'Connell, Kevin              0
1343  1998          Matthews, Shane              0
623   1984           Inverso, Glenn              0
628   1984              Kiel, Blair              0
1324  1998          Erickson, Craig              0
1322  1998            Dittoe, Chris              0
663   1985              Dils, Steve              0
659   1985        Christensen, Jeff              0
1318  1998           Delhomme, Jake              0
649   1984           Schroeder, Jay              0
646   1984               Reed, Mark              0
645   1984            Ransom, Brian              0
1768  2005             Ragone, Dave              0
643   1984           Pelluer, Steve              0
2283  2012          Enderle, Nathan              0
639   1984            Nugent, Terry              0
1765  2005            Palmer, Jesse              0
637   1984          Mathison, Bruce              0
2289  2012           Garrard, David              0
633   1984             Mackey, Kyle              0
2731  2016              Yates, T.J.              0
1463  2000              Rattay, Tim             -4

[2732 rows x 3 columns]

In [9]:
nfldata_df.groupby(lambda x: x.Year)['a'].agg(['sum', 'mean', 'max'])

AttributeError: 'int' object has no attribute 'Year'