In [5]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time

In [7]:

# File to Load (Remember to change these)
nfldata_csv = "C:/Users/admin/Documents/SMU/NFL-QB-Analytics/Assets/Data_Files/Cleaned_QB_data.csv"

# Read the City and Ride Data
nfldata = pd.read_csv(nfldata_csv)
nfldata.head()

   Year             Name          Season  TD Passes  Passing Yards  Wins
0  1970  Arrington, Rick  Regular Season          1            328     3
1  1970   Beathard, Pete  Regular Season          2            114     8
2  1970      Belden, Bob  Regular Season          0              0     2
3  1970  Cappleman, Bill  Regular Season          0             49     2
4  1970   Carter, Virgil      Postseason          0             64     0

In [9]:
nfldata_df = nfldata.groupby(["Year", "Name"])["Wins"].sum().reset_index().sort_values(by = "Wins",ascending = False)

nfldata_df

      Year                 Name  Wins
2605  2015          Newton, Cam    21
2446  2013      Wilson, Russell    21
2545  2015      Anderson, Derek    20
2663  2016     Garoppolo, Jimmy    20
2634  2015            Webb, Joe    20
1864  2007         Cassel, Matt    20
1859  2007           Brady, Tom    20
2389  2013    Jackson, Tarvaris    20
2023  2009          Brees, Drew    19
1559  2002          King, Shaun    18
1555  2002        Johnson, Brad    18
2243  2011       Rodgers, Aaron    18
608   1984      Cavanaugh, Matt    18
693   1985        Tomczak, Mike    18
2003  2008  Roethlisberger, Ben    18
2197  2011          Flynn, Matt    18
2620  2015      Siemian, Trevor    18
1557  2002         Johnson, Rob    18
2591  2015      Manning, Peyton    18
2405  2013      Manning, Peyton    18
2451  2014           Brady, Tom    18
2607  2015      Osweiler, Brock    18
1654  2004           Brady, Tom    17
2176  2011           Brady, Tom    17
2417  2013      Osweiler, Brock    17
2409  2013          McCoy, Colt    17
2208  2011         Hoyer, Brian    17
1832  2006          Orton, Kyle    17
1820  2006      Manning, Peyton    17
2219  2011        Mallett, Ryan    17
...    ...                  ...   ...
1823  2006      Matthews, Shane     0
1812  2006         Jacobs, Omar     0
1221  1996         George, Jeff     0
771   1987          Kelly, Paul     0
1765  2005        Palmer, Jesse     0
2192  2011       Edwards, Trent     0
2464  2014          Devlin, Pat     0
2463  2014     Davis, Dominique     0
2666  2016     Grayson, Garrett     0
2680  2016          Lewis, Thad     0
1932  2007           Vick, Mike     0
2440  2013    Vandenberg, James     0
777   1987       Lindley, David     0
1927  2007        Terrell, Jeff     0
2444  2013          Weber, Adam     0
2355  2012         Young, Vince     0
832   1988       Gelbaugh, Stan     0
1349  1998        Philcox, Todd     0
739   1987          Adams, Tony     0
2189  2011          Davis, Nate     0
1322  1998        Dittoe, Chris     0
481   1981          Dils, Steve     0
1310  1998          Baker, Jeff     0
1304  1997        Weldon, Casey     0
1293  1997        Philcox, Todd     0
2318  2012      Nesbitt, Joshua     0
1708  2004        Rivers, David     0
806   1987       Tinsley, Scott     0
1893  2007        Korrodi, Toby     0
1382  1999            Fox, Jeff     0

[2732 rows x 3 columns]

In [11]:
nfldata_df = nfldata.groupby(["Year", "Name"])["Passing Yards"].count().reset_index().sort_values(by = "Passing Yards",ascending = False)

nfldata_df

      Year                Name  Passing Yards
2423  2013      Rivers, Philip              4
2220  2011        Manning, Eli              4
1544  2002        Garcia, Jeff              4
2430  2013         Smith, Alex              4
2636  2015     Wilson, Russell              4
1543  2002        Gannon, Rich              4
1584  2002          Vick, Mike              4
1838  2006      Rivers, Philip              4
2036  2009        Favre, Brett              4
2446  2013     Wilson, Russell              4
2551  2015  Bridgewater, Teddy              4
2359  2013         Brees, Drew              4
2451  2014          Brady, Tom              4
2187  2011        Dalton, Andy              4
2548  2015          Brady, Tom              4
1539  2002        Favre, Brett              4
2177  2011         Brees, Drew              4
2176  2011          Brady, Tom              4
2461  2014        Dalton, Andy              4
2023  2009         Brees, Drew              4
2022  2009          Brady, Tom              4
2167  2010          Vick, Mike              4
1979  2008        Manning, Eli              4
1885  2007    Hasselbeck, Matt              4
2402  2013        Luck, Andrew              4
1555  2002       Johnson, Brad              4
1879  2007        Garcia, Jeff              4
2405  2013     Manning, Peyton              4
1563  2002     Manning, Peyton              4
1874  2007        Favre, Brett              4
...    ...                 ...            ...
1033  1992        O'Brien, Ken              1
1032  1992     Nagle, Browning              1
1031  1992    Marinovich, Todd              1
1029  1992      Majkowski, Don              1
1028  1992       Maddox, Tommy              1
1027  1992       Kosar, Bernie              1
1026  1992     Klingler, David              1
1024  1992       Johnson, Brad              1
1023  1992       Harbaugh, Jim              1
1022  1992        Goebel, Brad              1
1020  1992        George, Jeff              1
1019  1992      Gelbaugh, Stan              1
1016  1992       Francis, Jeff              1
1014  1992        Everett, Jim              1
1013  1992        Evans, Vince              1
1012  1992     Esiason, Boomer              1
1011  1992     Erickson, Craig              1
1010  1992         Elway, John              1
1009  1992        Elkins, Mike              1
1008  1992          Detmer, Ty              1
1007  1992       DeBerg, Steve              1
1006  1992     Chandler, Chris              1
1005  1992       Carlson, Jeff              1
1003  1992       Archer, David              1
1001  1991        Young, Steve              1
997   1991       Tomczak, Mike              1
995   1991   Testaverde, Vinny              1
993   1991      Secules, Scott              1
990   1991       Philcox, Todd              1
1366  1999         Banks, Tony              1

[2732 rows x 3 columns]